export const STOPPED_STATUS = 'stopped'
export const STOPPING_STATUS = 'stopping'
export const KILLING_STATUS = 'killing'
export const INSTALLING_STATUS = 'installing'
export const RUNNING_STATUS = 'running'
